using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;

namespace CDIM3312FinalProject.Models;

public static class SeedData
{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using var context = new AppDbContext(serviceProvider.GetRequiredService<DbContextOptions<AppDbContext>>());

        if (context.Products.Any()) 
        {
            return;
        }

        context.Products.AddRange(
            new Product { Name = "Nova X", Description = "This sleek, silver console with glowing blue accents is designed for high-performance gaming. It features a custom-designed CPU and GPU, potentially offering up to 12 teraflops of processing power, similar to the Xbox Series X. It boasts a minimalist aesthetic reminiscent of a spaceship cockpit, with curved edges and a transparent panel revealing internal components. It includes 16GB of GDDR6 RAM and a 1TB NVMe SSD for fast loading times. The Nova X supports 4K gaming at 120 FPS and includes ray tracing for enhanced visual fidelity. It also features advanced haptic feedback controllers and integrated Wi-Fi 6E for low-latency online gaming.", ImageURL = "img/novax.jpg",  },
            new Product { Name = "The Hyperion", Description = "This chunky, retro-inspired console in a vibrant shade of orange is built for nostalgic gamers. It features chunky buttons and a pixelated display, reminiscent of classic 8-bit and 16-bit consoles. Underneath its retro exterior, it houses a surprisingly powerful processor, capable of running modern indie games and emulating older titles flawlessly. The Hyperion includes 64GB of internal storage, expandable via SD card, and supports Bluetooth for wireless controllers. Its unique selling point is its focus on local multiplayer, with support for up to 8 players.", ImageURL = "img/thehyperion.jpg",  },
            new Product { Name = "The Quantum Leap", Description= "This vibrant purple console with intricate geometric patterns and angular lines is designed for cutting-edge virtual reality experiences. It is accompanied by a translucent, multi-colored controller, suggesting advanced motion tracking and haptic feedback. The Quantum Leap features a high-resolution display with a 120Hz refresh rate, perfect for VR gaming. It includes a powerful processor and ample RAM to handle demanding VR applications. The console also boasts advanced audio processing capabilities for immersive soundscapes.", ImageURL = "img/quantumleap.jpg",  },
            new Product { Name = "The Spectra", Description = "This console features a bioluminescent design, with sleek curves and soft, organic contours, encased in translucent material with intricate, flowing patterns, reminiscent of a futuristic piece of art. The Spectra is designed for streaming and cloud gaming, with a focus on accessibility and ease of use. It features a minimalist interface and supports voice control. The console includes a fast processor and integrated Wi-Fi 6 for seamless streaming. It also boasts a long-lasting battery for portable gaming.", ImageURL = "img/spectra.jpg", },
            new Product { Name = "Aether X", Description = "The Aether X is a sleek, powerful console for the modern gamer. Its black design with blue lights hints at its cutting-edge performance and stunning graphics. A purely digital platform, it offers fast downloads and a huge game library. The advanced controller provides immersive feedback. It's a gateway to high-fidelity gaming and future interactive experiences.", ImageURL = "img/aetherx.jpg", },
            new Product { Name = "Pixel Play", Description = "The PixelPlay Pop blends retro fun with modern ease. Its charming pink and white design features a vibrant, built-in HD screen. It plays both new indie games on stylish cartridges and updated classics. The wireless controller is comfortable and colorful. With online play and streaming, it's a unique console that's both nostalgic and fresh.", ImageURL = "img/pixelplay.jpg", },
            new Product { Name = "Vector X", Description = "The Vector X embodies the cutting edge of streamlined gaming innovation. Its sharp, obsidian black chassis, punctuated by dynamic neon blue vectors of light, speaks to its focused power and efficiency. At its heart lies an advanced quantum processor, delivering breathtakingly realistic visuals projected via a revolutionary holographic display that immerses players in vibrant, digital worlds. Eschewing physical clutter, the Vector X offers a purely digital experience with a massive terabyte-scale solid-state drive for instantaneous loading. The meticulously engineered controller features precise haptic feedback, integrated biometric authentication, and an optional neural interface, allowing for an unparalleled connection to the game. The Vector X isn't just a console; it's a precisely engineered instrument for experiencing the future of interactive entertainment.", ImageURL = "img/vectorx.jpg", },
            new Product { Name = "Synapse Deck", Description = "The Synapse Deck is a self-contained gaming hub designed for both immersive solo play and seamless social connectivity. Its angular, dark metallic chassis features vibrant cyan accents that highlight its futuristic aesthetic. The integrated, high-resolution holographic display projects crisp and dynamic visuals, offering a personal and captivating gaming experience. Intuitive touch controls flank the screen, providing quick access to menus and in-game actions, while integrated haptic feedback enhances tactile immersion. The Synapse Deck connects wirelessly to a global gaming network, facilitating instant access to a vast digital library and seamless multiplayer experiences. Its built-in spatial audio system delivers rich and directional sound, further drawing players into the game world. Compact yet powerful, the Synapse Deck represents a new era of personal gaming consoles.", ImageURL = "img/synapsedeck.jpg", },
            new Product { Name = "Resonance Station", Description = "The Resonance Station is designed to be the centerpiece of any entertainment setup, seamlessly blending gaming with immersive audio-visual experiences. Its sleek, low-profile design features a central high-definition screen flanked by integrated, high-fidelity stereo speakers. The console emphasizes a unified media experience, offering not only access to a vast digital game library but also streaming services and interactive entertainment applications. Control is primarily through voice commands and a minimalist touch interface embedded below the screen, creating a clean and uncluttered aesthetic. The Resonance Station aims to envelop the player in a rich soundscape and vibrant visuals, making it ideal for both solo adventures and shared entertainment.", ImageURL = "img/resonancestation.jpg", },
            new Product { Name = "Holo Scape X", Description = "The HoloScape X redefines immersive gaming with its stunning holographic displays and expansive curved monitor. The console's sleek, obsidian black chassis is accentuated by vibrant blue LED lights, creating a visually captivating aesthetic. The holographic displays project dynamic, pixelated landscapes and intricate circuitry, drawing players into the heart of the game. Connected to a curved, ultra-wide monitor, the HoloScape X delivers a panoramic gaming experience. Ergonomic controllers and a holographic keyboard provide intuitive control, while advanced audio processing creates a rich and realistic soundscape. The HoloScape X isn't just a console; it's a portal to new dimensions of interactive entertainment.", ImageURL = "img/holoscapex.jpg", },
            new Product { Name = "CyberStream X", Description = "The CyberStream X is a fusion of minimalist design and cyberpunk aesthetics, delivering a powerful and immersive gaming experience. Its sleek, dark metallic finish and sharp, geometric lines evoke a sense of futuristic technology. Glowing LED accents highlight the console's intricate details, while a large, curved screen displays vivid, action-packed game scenes. The CyberStream X offers seamless connectivity with wireless controllers and holographic displays, creating a dynamic and engaging environment. This console is designed for gamers who crave both style and substance, blending cutting-edge technology with a bold, cyberpunk-inspired look.", ImageURL = "img/cyberstreamx.jpg", },
            new Product { Name = "Aura Flow S", Description = "The AuraFlow S is a sleek and subtly powerful console designed to blend seamlessly into any modern entertainment setup. Its low-profile, dark grey chassis features dynamic cyan light strips that flow along its edges, creating a customizable ambient glow. The console prioritizes efficient performance and a quiet operation, utilizing advanced thermal design. While it boasts a minimalist physical presence, the AuraFlow S is engineered for high-fidelity gaming and smooth streaming of entertainment content. It supports both wireless and wired controllers and focuses on a refined user experience through an intuitive interface and seamless online connectivity. The AuraFlow S is about understated elegance and reliable performance.", ImageURL = "img/auraflows.jpg", },
            new Product { Name = "Cosmos Drive", Description = "The Cosmos Drive is a powerful and visually striking console designed to transport players to the edge of interactive entertainment. Its sleek, obsidian black exterior is accented by vibrant glowing blue lines that trace its contours, hinting at the advanced technology within. A dynamic, sci-fi-themed user interface is projected onto a holographic display, offering an immersive and intuitive experience. The console's design is reminiscent of a spacecraft, blending seamlessly into a futuristic environment. The Cosmos Drive is engineered for high-performance gaming and seamless connectivity, delivering a truly out-of-this-world experience.", ImageURL = "img/cosmosdrive.jpg", },
            new Product { Name = "Nova Edge", Description = "The Nova Edge is a cutting-edge console designed for the ultimate gaming experience. Its sleek, obsidian black finish is accented by glowing blue lines that pulse with energy, creating a visually stunning effect. A holographic display screen projects vibrant, sci-fi landscapes, immersing players in rich and detailed worlds. The console's minimalist design and sharp angles give it a futuristic aesthetic, reminiscent of a high-tech space station or laboratory. The Nova Edge is engineered for seamless performance and unparalleled immersion, delivering a gaming experience that is both powerful and elegant.", ImageURL = "img/novaedge.jpg", },
            new Product { Name = "Apex Pulse", Description = "The Apex Pulse is a state-of-the-art gaming console designed to deliver unparalleled immersion and performance. Its sleek, obsidian-black chassis is accented by vibrant neon lines that pulse with energy, creating a visually striking effect. A holographic display projects dynamic scenes from futuristic racing games, showcasing the console's cutting-edge graphics capabilities. The console rests on a minimalist white stand, and its surface is covered with intricate patterns that suggest advanced technology. The Apex Pulse seamlessly integrates into any technologically advanced environment, offering a clean and modern aesthetic.", ImageURL = "img/apexpulse.jpg", },
            new Product { Name = "Phantom Shift", Description = "The Phantom Shift is a revolutionary handheld gaming console that blends sleek ergonomics with cutting-edge holographic technology. In its expanded form, it features a vibrant, wide holographic display that projects stunning 3D visuals, seemingly floating above the device. The console's design incorporates comfortable, sculpted grips with intuitive control layouts, accented by dynamic neon blue and pink light strips that pulse with activity. A unique folding mechanism allows the Phantom Shift to collapse into a more compact form for portability, with the holographic display retracting seamlessly. This console is designed for gamers on the go who demand both high performance and a visually captivating experience.", ImageURL = "img/phantomshift.jpg", },
            new Product { Name = "Aetherium X", Description = "The Aetherium X redefines the gaming experience with its sophisticated design and advanced technology. The console's obsidian black chassis is accented with vibrant neon blue light strips that pulse with activity, creating a visually stunning effect. A key feature is its holographic display, which projects game scenes in dynamic 3D, adding a new layer of immersion. Designed for both performance and aesthetics, the Aetherium X is a centerpiece for any modern gaming setup.", ImageURL = "img/aetheriumx.jpg", },
            new Product { Name = "Apex Stream", Description = "The Apex Stream is engineered for the ultimate streaming and gaming experience. It features a hybrid architecture, combining local processing power with cloud-based rendering for unparalleled graphical fidelity. Designed with a focus on seamless connectivity, it integrates with all major streaming platforms and supports cross-platform play. The console boasts a minimalist design with customizable LED accents and a haptic feedback controller for enhanced immersion.", ImageURL = "img/apexstream.jpg", },
            new Product { Name = "Kryos", Description = "The Kryos is a high-performance gaming console designed with a focus on power and efficiency. Its dark, matte grey chassis features subtle geometric patterns and ventilation designed for optimal cooling. The console boasts a slot-loading disc drive and front-facing USB ports for easy connectivity. Its understated design aims to blend seamlessly into any entertainment setup while delivering top-tier gaming experiences.", ImageURL = "img/kryos.jpg", },
            new Product { Name = "Lumina", Description = "The Lumina is a sleek and modern gaming console characterized by its slim profile and vibrant, customizable LED lighting that wraps around its edges. Its minimalist design features a smooth, dark grey surface with subtle contours. The Lumina emphasizes both performance and aesthetics, aiming to be a stylish addition to any gaming setup while delivering a powerful gaming experience.", ImageURL = "img/lumina.jpg", },
            new Product { Name = "Nexus Core", Description = "The Nexus Core is a modular gaming and entertainment hub. The central unit is a sleek, compact device with a glowing core that pulses with energy. It wirelessly connects to various peripherals, including holographic projectors displaying game worlds and augmented reality overlays, and ergonomic controllers with advanced haptic feedback. The design emphasizes adaptability, allowing users to customize their setup based on their needs and preferences. The Nexus Core aims to be the central nervous system for all your interactive experiences.", ImageURL = "img/nexuscore.jpg", },
            new Product { Name = "Quantum Shift", Description = "The Quantum Shift is a sleek, minimalist console with a dark, matte finish and subtle, customizable RGB lighting that accents its contours. Its design emphasizes a clean and modern aesthetic. The console is engineered for high-performance gaming and features a slot-loading optical drive, multiple high-speed ports, and a wireless controller with advanced haptic feedback. The Quantum Shift aims to deliver a powerful and immersive gaming experience without unnecessary visual clutter.", ImageURL = "img/quantumshift.jpg", },
            new Product { Name = "Stratus", Description = "The Stratus console features a clean, horizontal design with a dark grey, almost gunmetal finish. Its form is rectangular with rounded edges, giving it a modern yet understated appearance. One end of the console has prominent horizontal ventilation slats, suggesting efficient cooling. The other end has a contrasting white or light grey triangular accent, adding a touch of visual interest. A subtle logo is visible on the side.", ImageURL = "img/stratus.jpg", },
            new Product { Name = "Nocturne X", Description = "The Nocturne X is a futuristic gaming console with a sleek, dark obsidian black exterior, boasting an angular design that emphasizes sharp lines and geometric shapes. The console's surface is subtly illuminated by integrated LED lights that cast a soft, cool blue glow, highlighting its intricate details.", ImageURL = "img/nocturnex.jpg", },
            new Product { Name = "Aegis", Description = "The Aegis console features a robust, rectangular design with a dark grey or black chassis. One end has a distinctive silver or light grey angular accent that adds a touch of modern flair. The front of the console is clean, with subtle indicators and a minimal number of ports visible. The overall design suggests a focus on durability and reliable performance.", ImageURL = "img/aegis.jpg", },
            new Product { Name = "Pundrax", Description = "The Pundrax console features a sleek, low-profile design with a matte black finish. Its front panel is characterized by sharp, intersecting lines that create a dynamic, geometric pattern. The console rests on small, circular feet, giving it a slightly elevated stance. Minimal ports are visible on the front, contributing to its clean aesthetic.", ImageURL = "img/pundrax.jpg", }


        );

        context.SaveChanges();

         Review NovaX = new Review {
            Score = 5,
            ReviewText = "The Nova X is a triumph of minimalist design and raw power. Its sleek, spaceship-inspired aesthetic is matched by its incredible performance. Games load in a flash thanks to the NVMe SSD, and the 4K visuals at 120 FPS with ray tracing are simply breathtaking. The haptic feedback controllers add a new layer of immersion. While the initial price point might be steep for some, the Nova X delivers a premium gaming experience that is hard to beat. The exclusive game library is still growing, but the titles available showcase the console's impressive capabilities.",
            Product = context.Products.Where(m => m.Name == "Nova X").Single()
        };
        context.Add(NovaX);
        context.SaveChanges();
    }
}